### PR TITLE
Rename Helm values for API gateway

### PR DESCRIPTION
**Pull request by markysoft**
https://eaflood.atlassian.net/browse/FPD-509
https://eaflood.atlassian.net/browse/FPD-516
https://eaflood.atlassian.net/browse/FPD-523
https://eaflood.atlassian.net/browse/FPD-530
https://eaflood.atlassian.net/browse/FPD-536
https://eaflood.atlassian.net/browse/FPD-543

Rename all text in Helm charts and values from `mine-support`  to `ffc-demo`

### CODE REVIEW

**Comment by johnwatson484** [comment]
Looks fine so far, but the description should also reference the user stories for changing the docker-compose, scripts and build.

**Comment by johnwatson484** [comment]
The production-values.yaml has the incorrect image name.

**Comment by djbingham** [comment]
`helm/Chart.yaml` references Mine Support in the description.

**Comment by markysoft** [comment]
> The production-values.yaml has the incorrect image name.

it's currently `jwminesupport.azurecr.io/ffc-demo-api-gateway:master`
what should it be?

**Comment by johnwatson484** [comment]
> > The production-values.yaml has the incorrect image name.
> 
> it's currently `jwminesupport.azurecr.io/ffc-demo-api-gateway:master`
> what should it be?

Apologies my mistake.  Thought it hadn't been changed.

**Review by johnwatson484 — APPROVED** [review]

**Pull request merged**
